project_id = "eqgouykzakjdmgmbnsca"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.sync-streaming-analytics]
    verify_jwt = false
  [functions.check-twitch-live]
    verify_jwt = false
